name: Build and Deploy Site

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to generate HTML
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python curation.py

      - name: Commit and push if it changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update static site"
            git push
          fi
