name: build-and-deploy

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour; adjust as needed
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access for pushing changes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 feedparser arxiv google-generativeai

      - name: Run script to generate HTML
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python curation.py

      - name: Commit and push if it changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add index
